IBM/platform-services-node-sdk

.travis.yml
global-search/v2.ts
global-tagging/v1.ts
test/integration/global-search.v2.test.js
test/integration/global-tagging.v1.test.js
test/integration/setUpHelper.js
test/unit/global-search.v2.test.js
test/unit/global-tagging.v1.test.js

This PR adds the global-search and global-tagging services to the project.
**Fixes:** n/a

Add new services to project

---

README.md
iam-access-groups/v2.ts
test/integration/iam-access-groups.v2.test.js
test/unit/iam-access-groups.v2.test.js

This PR adds the IAM Access Groups service, unit test and a skeleton integration test to the project.
**Fixes:** n/a

Add IAM Access Groups service and tests to the project

---

.travis.yml
global_catalog.env.enc
test/integration/global-catalog.v1.test.js

Adding tests for Global Catalog SDK.

test: add global catalog integration tests

---

test/integration/resource-manager.v2.test.js

**Fixes:** <! -- link to issue -->

test: add int tests for resource-manager

---

package-lock.json
package.json

Upgrade node core dependency to 2.4.0
**Fixes:** n/a

chore: upgrade version of node core

---

.gitignore
.travis.yml
README.md
global-catalog/v1.ts
global_catalog.env.enc
scripts/typedoc/generate_typedoc.sh
test/integration/global-catalog.v1.test.js
test/unit/global-catalog.v1.test.js

This PR adds the global-catalog service and unit test code to the project.
**Fixes:** n/a

feat(Global Catalog): add service and unit test code to project

---

.eslintignore
.eslintrc.js
package-lock.json
package.json
test/integration/global-catalog.v1.test.js
test/integration/global-search.v2.test.js
test/integration/global-tagging.v1.test.js
test/integration/iam-access-groups.v2.test.js
test/unit/common.test.js

This PR introduces more strict tslint and eslint rules, along with some code changes to fix linter failures.
**Fixes:** n/a

chore: introduce stricter lint rules

---

test/integration/iam-access-groups.v2.test.js

Additional changes that reduce the chance of test failures caused by parallel test runs.
- User ids are now unique
- Only old tests that failed to clean up or the current test group are cleaned up.
**Fixes:** https://github.ibm.com/IAM/uum/issues/2348
Integration tests have chances of intermittent failures.
Intermittent failures of integration tests are less likely/fixed.

test(IAM Access Groups): Additional fixes to reduce integration test failures

---

.travis.yml

This PR disables integration tests during tagged-release builds.

fix: disable integration tests in tagged-release builds

---

test/integration/case-management.v1.test.js

**Fixes:** <! -- link to issue -->

feat(case management): added integration tests to NodeJS SDK

---

test/integration/enterprise-management.v1.test.js

This PR fixes the EnterpriseManagement integration test.

test: use correct date format with account helper operations

---

test/integration/iam-policy-management.v1.test.js

Added integration test fo rPolicy and role management service
**Fixes:** <! -- link to issue -->

Added integration test for Policy and role management service

---

.travis.yml

Disables int tests for EM and RM services until they can be fixed.

build: disable EM and RM tests until fixed

---

global-catalog/v1.ts
global-search/v2.ts
global-tagging/v1.ts
package-lock.json
test/unit/case-management.v1.test.js
test/unit/global-catalog.v1.test.js
test/unit/global-search.v2.test.js
test/unit/global-tagging.v1.test.js

This PR contains a re-gen of some of the services

Regen svcs

---

.travis.yml
test/integration/catalog-management.v1.test.js

Disables integration tests in travis builds because they are too unreliable

Disable its

---

package-lock.json
package.json
test/integration/catalog-management.v1.test.js
test/integration/open-service-broker.v1.test.js

This PR contains minor fixes to the case-management and catalog-management integration tests and upgrades the node core to v2.4.1.

test: fix catalog-mgmt and osb int tests

---

README.md
scripts/typedoc/generate_typedoc.sh
test/integration/user-management.v1.test.js
test/unit/user-management.v1.test.js
user-management/v1.ts

This PR adds the User Management service to the project.

feat(User Management): add service to project

---

.gitignore
README.md
configuration-governance/v1.ts
examples/configuration-governance.v1.test.js
scripts/typedoc/generate_typedoc.sh
test/integration/configuration-governance.v1.test.js
test/unit/configuration-governance.v1.test.js

This PR adds the Configuration Governance service to the project.

feat(Configuration Governance): add service to project

---

test/unit/user-management.v1.test.js
user-management/v1.ts

This PR contains a re-gen of the User Management service.

fix(User Management): re-gen user-mgmt service

---

examples/global-tagging.v1.test.js
global-tagging/v1.ts
test/integration/global-tagging.v1.test.js
test/unit/global-tagging.v1.test.js

This PR includes:
* re-gen of Global Tagging service and unit test code
* a renovated integration test
* a new working request examples "test"

fix(Global Tagging): re-gen service using latest API definition

---

.gitignore
README.md
examples/iam-identity.v1.test.js
iam-identity/v1.ts
scripts/typedoc/generate_typedoc.sh
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

This PR adds the IAM Identity service to the project.

feat(IAM Identity): add service to project

---

iam-identity/v1.ts
package-lock.json
package.json
test/integration/global-catalog.v1.test.js
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

This PR contains a regen of the IAM Identity service after recent API definition updates.

fix(IAM Identity): re-gen service after API definition updates

---

case-management/v1.ts
catalog-management/v1.ts
configuration-governance/v1.ts
enterprise-management/v1.ts
global-catalog/v1.ts
global-search/v2.ts
global-tagging/v1.ts
iam-access-groups/v2.ts
iam-identity/v1.ts
iam-policy-management/v1.ts
open-service-broker/v1.ts
resource-controller/v2.ts
resource-manager/v2.ts
test/unit/catalog-management.v1.test.js
user-management/v1.ts

This PR contains a re-gen of each of the services, including an update to Resource Controller after recent API chagnes.

fix: regen services with latest SDK generator

---

README.md
examples/usage-reports.v4.test.js
scripts/typedoc/generate_typedoc.sh
test/integration/usage-reports.v4.test.js
test/unit/usage-reports.v4.test.js
usage-reports/v4.ts

This PR adds the Usage Reports service to the project, including integration tests and working examples.

feat(Usage Reports): add service to project

---

.gitignore
README.md
enterprise-usage-reports/v1.ts
examples/enterprise-usage-reports.v1.test.js
scripts/typedoc/generate_typedoc.sh
test/integration/enterprise-usage-reports.v1.test.js
test/integration/iam-identity.v1.test.js
test/unit/enterprise-usage-reports.v1.test.js

This PR adds the Enterprise Usage Reports service to the project, including integration tests and examples.

feat(Enterprise Usage Reports): add service to project

---

configuration-governance/v1.ts
examples/configuration-governance.v1.test.js
test/integration/configuration-governance.v1.test.js
test/unit/configuration-governance.v1.test.js

Updates Configuration Governance service after recent API changes.

fix(Configuration Governance): update service after API changes

---

examples/configuration-governance.v1.test.js
examples/iam-access-groups.v2.test.js
iam-access-groups/v2.ts

Updates the IAM Access Groups service and adds working examples.

fix(IAM Access Groups): update service and add examples

---

iam-identity/v1.ts
package.json
test/unit/iam-identity.v1.test.js

This PR contains a re-gen of IAM Identity after recent API updates.

update IAM Identity

---

.releaserc
global-catalog/v1.ts

Re-gen of the Global Catalog service after recent API changes.

fix(Global Catalog): re-gen service after recent API changes

---

examples/open-service-broker.v1.test.js
examples/resource-controller.v2.test.js
test/integration/resource-controller.v2.test.js

This PR adds examples for Open Service Broker and Resource Controller.

test: add examples for osb & rc services

---

test/integration/user-management.v1.test.js
test/unit/user-management.v1.test.js
user-management/v1.ts

This PR contains a re-gen of the User Management service plus updates to the integration tests after recent changes to the API.

fix(User Management): re-gen service and update tests after API changes

---

.gitignore
README.md
enterprise-billing-units/v1.ts
examples/enterprise-billing-units.v1.test.js
scripts/typedoc/generate_typedoc.sh
test/integration/configuration-governance.v1.test.js
test/integration/enterprise-billing-units.v1.test.js
test/unit/enterprise-billing-units.v1.test.js

Adds the Enterprise Billing Units service to the project.

feat(Enterprise Billing Units): add service to project

---

package-lock.json
package.json

Fixes the vulnerability associated with highlight.js

fix: avoid highlight.js vulnerability

---

.gitignore
README.md
examples/usage-metering.v4.test.js
scripts/typedoc/generate_typedoc.sh
test/integration/usage-metering.v4.test.js
test/unit/usage-metering.v4.test.js
usage-metering/v4.ts

This PR adds the Usage Metering service to the project.

feat(Usage Metering): add service to project

---

case-management/v1.ts
configuration-governance/v1.ts
enterprise-billing-units/v1.ts
enterprise-management/v1.ts
enterprise-usage-reports/v1.ts
examples/global-search.v2.test.js
global-catalog/v1.ts
global-search/v2.ts
global-tagging/v1.ts
test/integration/global-search.v2.test.js

This PR contains a re-gen of several services and adds examples for the Global Search service.

re-gen services and add examples

---

package-lock.json
package.json

This PR upgrades some dependencies to avoid security vulnerabilities

fix(build): upgrade dependencies to avoid vulnerabilities

---

package-lock.json
package.json

Updates jest version to avoid alert for node-notifier dependency

fix(build): update jest version to avoid vulnerability

---

iam-access-groups/v2.ts
test/unit/iam-access-groups.v2.test.js

Re-gen of IAM Access Groups service...

fix(IAM Access Groups): minor code re-gen after recent API changes

---

configuration-governance/v1.ts
examples/configuration-governance.v1.test.js
test/unit/configuration-governance.v1.test.js

**Fixes:** <! -- link to issue -->

fix(Configuration Governance): re-gen service after recent API changes

---

examples/global-tagging.v1.test.js
global-tagging/v1.ts
test/integration/global-tagging.v1.test.js
test/unit/global-tagging.v1.test.js

This PR updates the Global Tagging service after recent changes to the API definition.

fix(Global Tagging): update service after recent API changes

---

test/integration/case-management.v1.test.js

This PR removes PII from the case management integration test

test(Case Management): remove PII from case-mgmt integration test

---

case-management/v1.ts
examples/case-management.v1.test.js
package-lock.json
package.json
test/unit/case-management.v1.test.js

This PR adds examples to the Case Management service.

fix(Case Management): re-gen service and add examples

---

examples/global-catalog.v1.test.js
global-catalog/v1.ts
package-lock.json
package.json
test/unit/global-catalog.v1.test.js

This PR contains a re-gen of the Global Catalog service plus new working examples.

fix(Global Catalog): re-gen service and add examples

---

package-lock.json
package.json

Upgrades the node core dependency to version 2.8.0

fix(build): upgrade to latest node core library

---

examples/user-management.v1.test.js
test/integration/user-management.v1.test.js

This PR adds examples to the User Management service and move hard-coded config values to the env file.

fix(User Management): add examples

---

.travis.yml
package-lock.json
package.json

This PR upgrades our npm and semrel dependencies to the current most recent versions.

build: use latest versions of npm and semantic-release

---

examples/resource-controller.v2.test.js
package-lock.json
resource-controller/v2.ts
test/integration/resource-controller.v2.test.js
test/unit/resource-controller.v2.test.js

This PR contains a re-gen of the Resource Controller service and unit test code, along with updates to the integration tests and examples.

fix(Resource Controller): update service after recent API changes

---

.secrets.baseline
examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

This PR updates the IAM Identity service - including integration tests and examples - after recent changes to the API definition.

fix(IAM Identity): update service after recent API changes

---

examples/case-management.v1.test.js
examples/configuration-governance.v1.test.js
examples/enterprise-billing-units.v1.test.js
examples/enterprise-usage-reports.v1.test.js
examples/global-catalog.v1.test.js
examples/global-search.v2.test.js
examples/global-tagging.v1.test.js
examples/iam-access-groups.v2.test.js
examples/iam-identity.v1.test.js
examples/iam-policy-management.v1.test.js
examples/open-service-broker.v1.test.js
examples/resource-controller.v2.test.js
examples/resource-manager.v2.test.js
examples/usage-metering.v4.test.js
examples/usage-reports.v4.test.js
examples/user-management.v1.test.js

This PR adds labels to example output. This way it is easier to identify which output section belongs to which method.

fix: add labels to example output

---

global-search/v2.ts

fix(Global Search): update Global Search SDK after Api definition changes

---

examples/resource-controller.v2.test.js

This PR modifies the Resource Controller working examples so that the labels displayed in the output will not be included in the API reference.

chore: hide labels from API reference

---

resource-controller/v2.ts
test/unit/resource-controller.v2.test.js

fix(resource controller): update sdk after recent api changes

---

iam-access-groups/v2.ts
test/unit/iam-access-groups.v2.test.js

fix(iam access groups): update sdk after recent api changes

---

CODE_OF_CONDUCT.md
package-lock.json
package.json

Updates the version of a couple dependencies.

build: upgrade semrel and node core dependencies

---

enterprise-management/v1.ts
test/unit/enterprise-management.v1.test.js

Re-gen of service after API changes.

fix(Enterprise Management): update service after API changes

---

examples/case-management.v1.test.js
examples/configuration-governance.v1.test.js
examples/enterprise-billing-units.v1.test.js
examples/enterprise-management.v1.test.js
examples/enterprise-usage-reports.v1.test.js
examples/global-catalog.v1.test.js
examples/global-search.v2.test.js
examples/global-tagging.v1.test.js
examples/iam-access-groups.v2.test.js
examples/iam-identity.v1.test.js
examples/iam-policy-management.v1.test.js
examples/open-service-broker.v1.test.js
examples/posture-management.v1.test.js
examples/resource-manager.v2.test.js
examples/usage-metering.v4.test.js
examples/usage-reports.v4.test.js
examples/user-management.v1.test.js

fix: example labels

---

package-lock.json

Updates version of the trim-newlines dependency to avoid vulnerability alerts.

build(deps): bump version of trim-newlines to avoid alerts

---

iam-identity/v1.ts

fix(IAM Identity): re-gen service after recent API changes

---

package-lock.json
package.json

This PR upgrades the node core dependency to 2.11.3

build: upgrade node core dependency to 2.11.3

---

iam-access-groups/v2.ts
test/unit/iam-access-groups.v2.test.js

fix(IAM Access Groups): update service after recent api changes

---

.gitignore
README.md
examples/ibm-cloud-shell.v1.test.js
ibm-cloud-shell/v1.ts
scripts/typedoc/generate_typedoc.sh
test/integration/ibm-cloud-shell.v1.test.js
test/unit/ibm-cloud-shell.v1.test.js

feat(Cloudshell): add service, tests and examples to project

---

package.json

fix: public publish to org

---

package.json

fix: add public publish option

---

test/unit/usage-reports.v4.test.js
usage-reports/v4.ts

add optional name parameters to data type
Names will now show up when the optional parameter _names is passed

fix(Usage Reports): add optional name parameters to struct

---

package-lock.json

This PR updated package-lock.json to bump dependencies and avoid vulnerability alerts.

fix: update dependencies to avoid vulnerability alerts

---

examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

feat(iam-identity): fixing examples

---

package-lock.json
package.json

Bumps up axios version to 0.21.4 to avoid alerts

fix(build): bump axios version to avoid vulnerability alerts

---

package-lock.json

fix(build): update dependencies

---

package-lock.json

bumps ansi-regex version to 5.0.1 to address a security vulnerability
to produce an updated package-lock.json, I did this in my local sandbox:
```
rm -fr node_modules package-lock.json
npm install
```
then I committed the updated package-lock.json

chore(deps): bump ansi-regex to 5.0.1

---

.travis.yml
package.json

This PR removes codecov from the project due to security vulnerabilities.

build: remove codecov from project

---

.secrets.baseline
iam-access-groups/v2.ts
package-lock.json
test/unit/iam-access-groups.v2.test.js

fix(IAM Access Groups): update service after service url adjustment

---

iam-access-groups/v2.ts
test/unit/iam-access-groups.v2.test.js

Added new member type to include in AG member list. also updated related examples.

fix(IAM Access Groups): add new member trusted profile

---

package-lock.json
package.json

This PR refreshes dependencies to avoid a vulnerability reported in the follow-redirects 2nd order dependency.

fix: bump dependencies to avoid follow-redirects vuln

---

package-lock.json
package.json

This PR bumps a few dependencies to avoid security vulnerabilities

fix: bump dependencies to avoid vulnerabilities

---

iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

The report schema is slightly improvised, incorporating the changes into SDKs

fix(IAM Identity): update report schema and fix ITs

---

context-based-restrictions/v1.ts
examples/context-based-restrictions.v1.test.js
test/integration/context-based-restrictions.v1.test.js
test/unit/context-based-restrictions.v1.test.js

Add ability to query by rule enforcement modes (previously released) and add features needed for Context-based Restrictions rule API types.
- feat(Context-based Restrictions): add enforcement_mode query param
- feat(Context-based Restrictions): add service ref address location support
- feat(Context-based Restrictions): add rule API type support

add latest Context-based Restrictions features

---

package-lock.json
package.json

Bump node sdk core dependency to avoid file-type vulnerability SNYK-JS-FILETYPE-2958042

chore: bump core version to avoid file-type vuln

---

examples/context-based-restrictions.v1.test.js

Signed-off-by: Stephen SooHoo <soohoos@us.ibm.com>
Better SDK example alignment with curl examples.

refactor(Context-based Restrictions): update create zone examples

---

case-management/v1.ts
examples/case-management.v1.test.js
package-lock.json
package.json
test/integration/case-management.v1.test.js
test/unit/case-management.v1.test.js

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK
generator.

fix(Case Management): regen service to add Pager

---

.secrets.baseline
examples/iam-access-groups.v2.test.js
iam-access-groups/v2.ts
test/integration/iam-access-groups.v2.test.js
test/unit/iam-access-groups.v2.test.js

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.

fix(IAM Access Groups): regen service to get Pagers

---

.secrets.baseline
examples/resource-controller.v2.test.js
resource-controller/v2.ts
test/integration/resource-controller.v2.test.js
test/unit/resource-controller.v2.test.js

This commit contains a re-gen of the Resource Controller service
to leverage the new Pagers emitted by the SDK generator.

fix(Resource Controller): re-gen service to get new Pagers

---

.secrets.baseline
enterprise-management/v1.ts
examples/enterprise-management.v1.test.js
test/integration/enterprise-management.v1.test.js
test/unit/enterprise-management.v1.test.js

This commit contains a re-gen of the Enterprise Management service to leverage the new Pagers emitted by the SDK generator.

fix(Enterprise Management): re-gen service to get new Pagers

---

.secrets.baseline
examples/user-management.v1.test.js
test/integration/user-management.v1.test.js
test/unit/user-management.v1.test.js
user-management/v1.ts

This commit contains a re-gen of the User Management service to leverage the new Pagers emitted by the SDK generator.

fix(User Management): re-gen service to get new Pagers

---

examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

Signed-off-by: poorani <poorani.senthilkumar.sankari@ibm.com>
Adding user exception list and token lifetime to IAM account settings
Adding user exception list and token lifetime to IAM account settings

feat(IAM Identity): adding userExpm list and token lifetime

---

.travis.yml
README.md
package.json

This commit modifies the build to use node versions 14, 16 and 18, and bumps our min version of node from 12 to 14.

feat: bump min node version to 14

---

package-lock.json
package.json

This PR bumps the node core to 4.0.2 to avoid vulnerabilities

build: bump node core to avoid vulnerabilities

---

iam-policy-management/v1.ts
test/integration/iam-policy-management.v1.test.js
test/unit/iam-policy-management.v1.test.js

V2Roles to support optional query parameter service_group_id
Fixed replacePolicy example
PR's are merged:
Staging: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/162
Production: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/163
https://github.ibm.com/IAM/AM-issues/issues/645

feat(IAM Policy Management): support of new query param source_group_id for v2/roles

---

package-lock.json
package.json

Bumps node core version to 4.0.5

build: bump node core version to 4.0.5

---

CONTRIBUTING.md
package.json
update_service.md

This PR adds detailed instructions on how to update a service contained in the SDK project.

docs: add update_service.md

---

enterprise-billing-units/v1.ts
examples/enterprise-billing-units.v1.test.js
test/integration/enterprise-billing-units.v1.test.js
test/unit/enterprise-billing-units.v1.test.js

Adds start and limit parameters to support pagination for certain Enterprise Billing Units APIs
Results can now be optionally paginated using the start and limit parameters.
```
PASS  test/unit/enterprise-billing-units.v1.test.js
--------------------------|---------|----------|---------|---------|-----------------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s           
--------------------------|---------|----------|---------|---------|-----------------------------
All files                 |   96.19 |    78.57 |     100 |    95.9 |                             
enterprise-billing-units |   95.97 |    78.57 |     100 |   95.65 |                             
v1.ts …
```

feat(Enterprise Billing Units): add start and limit parameters to billing unit APIs

---

examples/user-management.v1.test.js
test/integration/user-management.v1.test.js
test/unit/user-management.v1.test.js
user-management/v1.ts

Update Include_settings and substring search functionality (User Management) 
the current issue for updating SDK https://github.ibm.com/IAM/uum/issues/5882 
the previous issue for the user management code change https://github.ibm.com/IAM/uum/issues/4948

feat (User Management): add query params search and include_settings to list_users operation

---

.travis.yml
package-lock.json
package.json

Bumps our version of semantic-release to avoid the "semver" vulnerability.

build: bump semantic-release to avoid vulnerabilities

---

update_service.md

docs: fix update_service.md

---

examples/iam-access-groups.v2.test.js
iam-access-groups/v2.ts
test/integration/iam-access-groups.v2.test.js
test/unit/iam-access-groups.v2.test.js

SDK adopters will be able to call access group template and assignment APIs.
API Definition
[Stage](https://test.cloud.ibm.com/docs/access-groups)
[Production](https://cloud.ibm.com/docs/access-groups)
Tests:
Examples:
Integration Tests:

feat (IAM Access Groups): Add support for access group templates

---

.prettierrc.js
CONTRIBUTING.md
update_service.md

This PR modifies the project to enable developers to build and test on Windows.

fix: enable builds on Windows

---

examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

Added support for IAM enterprise feature. Enterprise admins can create templates for account settings and trusted profiles and assign them to accounts and account groups in the enterprise.
SDK adopters will be able to work with IAM enterprise feature.
API definition: [Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api#list-profile-templates)
Test information:
Unit tests:
```
npm run test-unit
> @ibm-cloud/platform-services@0.38.0 test-unit
> npm run build && jest test/unit/
> @ibm-cloud/platform-services@0.38.0 build
> tsc && cp package.json dist/
PASS test/unit/iam-policy-management.v1.test.js (12.74 s)
PASS test/unit/catalog-management.v1.test.js (13.133 s)
PASS …
```

feat(IAM Identity): Add support for IAM enterprise

---

examples/iam-access-groups.v2.test.js
iam-access-groups/v2.ts
test/integration/iam-access-groups.v2.test.js
test/unit/iam-access-groups.v2.test.js

Removed "update" field from create template & template version request body.

fix(IAM Access Groups): Remove update action control from assertions

---

context-based-restrictions/v1.ts
examples/context-based-restrictions.v1.test.js
test/integration/context-based-restrictions.v1.test.js
test/unit/context-based-restrictions.v1.test.js

Adds service group support to operations
Should replace https://github.com/IBM/platform-services-node-sdk/pull/223
service_name parameter can now be replaced with the service group parameter.

feat(Context-Based Restrictions): add service group support to Operations

---

.secrets.baseline

build: fix detect-secrets issue

---

test/unit/usage-reports.v4.test.js
usage-reports/v4.ts

Add new query parameters to support pagination of API: /v1/billing-reports-snapshots

feat(Usage Reports): Update query param for getting reports snapshotlist

---

iam-policy-management/v1.ts

Updated based on API definition fix to allow for `conditions` under `rule.conditions`.
Tests:
Examples:
```sh
jest test examples/iam-policy-management.v1.test.js
PASS  examples/iam-policy-management.v1.test.js (14.636 s) ...
-----------------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------------------------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                                   
-----------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------- …
```

fix(IAM Policy Management): Added nest conditions to rule.conditions

---

.secrets.baseline
package-lock.json
package.json

Bumps our node core version to the latest.

fix: bump node core version to 4.1.4

---

context-based-restrictions/v1.ts
examples/context-based-restrictions.v1.test.js
test/unit/context-based-restrictions.v1.test.js

- add new field to /v1/operations response
- fix zone example values
- support /v1/operations 'enforcement_modes' response field
- add IPv6 examples for doc/SDK consistency

feat(Context-Based Restrictions): add enforcement_modes to operations response

---

examples/usage-reports.v4.test.js
test/integration/usage-reports.v4.test.js
test/unit/usage-reports.v4.test.js
usage-reports/v4.ts

Adding new API to validate s2s authentication in billing snapshot configuration service in usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/services/billing/apptio-integration.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2102

feat(Usage Reports): add billing snapshot config validate service to usage reports

---

.gitignore
.secrets.baseline
package-lock.json
package.json

Bumps the node core to the latest version to address axios-related vulnerabilities.

fix(deps): bump node core to 4.2.2

---

iam-policy-management/v1.ts
test/integration/iam-policy-management.v1.test.js
test/unit/iam-policy-management.v1.test.js

issue: https://github.ibm.com/IAM/AM-issues/issues/1949)

feat(IAM Policy Management): re-gen service after fix the template sate parameter

---

iam-policy-management/v1.ts

Issue: https://github.ibm.com/IAM/AM-issues/issues/2140
Minor fix of subject attribute value type to match API and other attributes value type.
Subject attribute value should not be limited to a string, but should allow for other types based on API. This change allows that.
integration tests:
```sh  PASS  test/integration/iam-policy-management.v1.test.js (31.717 s)
-----------------------|---------|----------|---------|---------|------------------------------------------------------------------------------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```

fix(IAM Policy Management): update subject attribute value

---

.gitignore
README.md
examples/partner-usage-reports.v1.test.js
partner-usage-reports/v1.ts
test/integration/partner-usage-reports.v1.test.js
test/unit/partner-usage-reports.v1.test.js

Adding new partner API to fetch resource usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/cosell/partner.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2063

feat(Partner Usage Reports): add resource usage reports to partners

---

examples/iam-policy-management.v1.test.js
iam-policy-management/v1.ts
test/unit/iam-policy-management.v1.test.js

This is a minor regeneration based on update to enum for operators in v2/policies.
Issue: https://github.ibm.com/IAM/AM-issues/issues/2212
Also updated missed etag headers from previous issue: https://github.ibm.com/IAM/AM-issues/issues/2001
Tests:
```sh
jest test/integration/iam-policy-management.v1.test.js 
...
PASS  test/integration/iam-policy-management.v1.test.js (22.178 s)
-----------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```

fix(IAM Policy Management): regenerate based on minor API update to operator

---

context-based-restrictions/v1.ts
examples/context-based-restrictions.v1.test.js
test/integration/context-based-restrictions.v1.test.js
test/unit/context-based-restrictions.v1.test.js

Add support for new endpoint
Update examples to match the API
Adds new endpoint for singular service ref target

 feat(Context-Based Restrictions): add Service Ref Target

---

enterprise-management/v1.ts
test/integration/enterprise-management.v1.test.js
test/unit/enterprise-management.v1.test.js

Added options field in create account payload

fix(Enterprise Management): add options property to create_account payload

---

global-search/v2.ts
global-tagging/v1.ts
test/integration/global-search.v2.test.js
test/unit/global-search.v2.test.js
test/unit/global-tagging.v1.test.js

Removed all references to transaction-id

fix(Global Search & Tagging): re-gen services with latest API definition

---

examples/iam-policy-management.v1.test.js
iam-policy-management/v1.ts
test/integration/iam-policy-management.v1.test.js
test/unit/iam-policy-management.v1.test.js

Authorization policy type support for enterprise accounts
issue: https://github.ibm.com/IAM/AM-issues/issues/2350
test results:
examples:

feat(IAM Policy Management): S2S support for enterprise accounts

---

enterprise-management/v1.ts

Update create Account Response payload in enterprise child

fix(Enterprise Management): update create_account response payload

---

enterprise-management/v1.ts

Re-Generated sdk after recent create_account response changes in create enterprise child account api

fix(Enterprise Management): re-gen service after recent create_account response changes

---

catalog-management/v1.ts
examples/catalog-management.v1.test.js
test/integration/catalog-management.v1.test.js
test/unit/catalog-management.v1.test.js

regenerating after recent api changes
adding new endpoints, removing some deprecated fields

feat(Catalog Management): regen after recent api changes

---

global-search/v2.ts
test/unit/global-search.v2.test.js

Updated documentation about project onboarding.

fix(Global Search): add support for is_project_resource query param

---

package-lock.json
package.json
test/unit/case-management.v1.test.js
test/unit/catalog-management.v1.test.js
test/unit/context-based-restrictions.v1.test.js
test/unit/enterprise-billing-units.v1.test.js
test/unit/enterprise-management.v1.test.js
test/unit/enterprise-usage-reports.v1.test.js
test/unit/global-catalog.v1.test.js
test/unit/global-search.v2.test.js
test/unit/global-tagging.v1.test.js
test/unit/iam-access-groups.v2.test.js
test/unit/iam-identity.v1.test.js
test/unit/iam-policy-management.v1.test.js
test/unit/ibm-cloud-shell.v1.test.js
test/unit/open-service-broker.v1.test.js
test/unit/partner-billing-units.v1.test.js
test/unit/partner-usage-reports.v1.test.js
test/unit/resource-controller.v2.test.js
test/unit/resource-manager.v2.test.js
test/unit/usage-metering.v4.test.js
test/unit/usage-reports.v4.test.js
test/unit/user-management.v1.test.js

This commit simply adds a dependency on the newly-published @ibm-cloud/sdk-test-utilities package and modifies the generated unit test code slightly to use this new package instead of getting the test utility functions from the node core dependency.

test: use new sdk-test-utilities package in unit tests

---

.travis.yml
README.md
package-lock.json
package.json

This commit bumps the node core dependency to 5.0.0, and also bumps the min supported version of node to be 18.

feat: bump node core to 5.0.0

---

global-tagging/v1.ts
test/unit/global-search.v2.test.js
test/unit/global-tagging.v1.test.js

fix(Global Tagging): add 'update' option to attach_tag operation

---

resource-controller/v2.ts
test/integration/resource-controller.v2.test.js
test/unit/resource-controller.v2.test.js

feat(Resource Controller): add "onetime_credentials" property in ResourceInstance and ResourceKey schemas

---

resource-controller/v2.ts

feat(Resource Controller): deprecate alias, bindings APIs, and related schema items

---

catalog-management/v1.ts
examples/catalog-management.v1.test.js
test/integration/catalog-management.v1.test.js
test/unit/catalog-management.v1.test.js

Regenerating after recent API changes
No modifications, just adding new endpoints and parameters.
example:
```
Tests:       52 passed, 52 total
Time:        25.125 s
Ran all test suites matching /examples\/catalog-management.v1.test.js/i.
```
integration:
```
Test Suites: 20 skipped, 1 passed, 1 of 21 total
Tests:       407 skipped, 56 passed, 463 total
Time:        34.431 s, estimated 46 s
Ran all test suites matching /test\/integration\//i.
```

feat(Catalog Management): re-gen service after recent API changes

---

catalog-management/v1.ts
examples/catalog-management.v1.test.js
test/integration/catalog-management.v1.test.js
test/unit/catalog-management.v1.test.js

Regenerating after fixing API definition for the region filter under a catalog account.
Previous behavior had invalid fields for the account type, new behavior fixes that.
Integration
```
Test Suites: 19 skipped, 1 passed, 1 of 20 total
Tests:       406 skipped, 57 passed, 463 total
Time:        26.726 s, estimated 32 s
Ran all test suites matching /test\/integration\//i.
```
Examples
```
Tests:       52 passed, 52 total
Time:        22.512 s
Ran all test suites matching /examples\/catalog-management.v1.test.js/i.
```

fix: fix catalog account region filter fields

---

iam-access-groups/v2.ts
test/unit/iam-access-groups.v2.test.js

feat(IAM Access Groups): Add CRN filter

---

examples/global-catalog.v1.test.js
global-catalog/v1.ts
test/integration/global-catalog.v1.test.js
test/unit/global-catalog.v1.test.js

Regenerating to fix issue with `price` field in `Price` struct capitalization. Also includes addition of `deployment_regions` field in pricing data, and `url` field in update object..
Fixes ability to access price data from get pricing function.
Example tests
```
Tests:       15 passed, 15 total
Time:        4.543 s
Ran all test suites matching /examples\/global-catalog.v1.test.js/i.
```
Integration tests
```
Test Suites: 19 skipped, 1 passed, 1 of 20 total
Tests:       440 skipped, 27 passed, 467 total
Time:        17.092 s
Ran all test suites matching /test\/integration\//i.
```

fix(Global Catalog): fix price field capitalization

---

iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

added filter parameter to the search api e.g. list apikeys, list serviceid, and list trusted profile
```Test Suites: 1 passed, 1 total
Tests:       70 passed, 70 total
Time:        790.315 s
Ran all test suites matching /test\\integration\\iam-identity.v1.test.js/i.
```

feat(IAM Identity): add filter parameter for search api

---

examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

Includes serviceID Groups api
Trusted profile email field is added

feat(IAM Identity): adding serviceId Groups API

---

examples/iam-identity.v1.test.js
iam-identity/v1.ts
test/integration/iam-identity.v1.test.js
test/unit/iam-identity.v1.test.js

delete trusted profile link with parameters api
```
Tests:       76 passed, 76 total
Time:        445.146 s, estimated 451 s
Ran all test suites matching /test\\integration\\iam-identity.v1.test.js/i.
```

fix(IAM Identity): add delete link with parameter api

---

global-search/v2.ts
test/unit/global-search.v2.test.js

fix(Global Search): regenerated services with latest API definition
