IBM/platform-services-node-sdk

.travis.yml
This PR adds a change to run integration tests only on one of the two parallel builds (node 12)
**Fixes:** n/a
=> chore: run integration tests only on node 12 build

package-lock.json, package.json, tsconfig.json
Upgrades the node core to 2.4.5 and removes dependencies on `@types/extend` and `@types/isstream` which are not needed.
=> chore: upgrade node core to 2.4.5

examples/resource-manager.v2.test.js, resource-manager/v2.ts, test/integration/resource-manager.v2.test.js, test/unit/resource-manager.v2.test.js
This PR updates the Resource Manager service, adds examples and move configuration values out from tests into a configuration file.
=> fix(Resource Manager): update service after recent API changes and generate examples

.travis.yml
Node 10 is deprecated, so we want to update the build to use the latest stable versions of Node, 12 and 14.
=> build: remove deprecated Node 10 version from CI build

README.md, package.json
Changes in this PR are going to 
- change `ibm-platform-services` package name to `platform-services`, and 
- move it to `@ibm-cloud` organisation
- update README according to the above changes
From this point forward the package is `@ibm-cloud/platform-services`.
=> fix: move ibm-platform-services package to @ibm-cloud npm org

package-lock.json, package.json
This PR bumps the node core version to 2.12.2 to pull in the ContainerAuthenticator functionality.
=> fix: bump node core version to 2.12.2

examples/iam-identity.v1.test.js, package-lock.json
=> docs: fix documentation

context-based-restrictions/v1.ts, test/integration/context-based-restrictions.v1.test.js, test/unit/context-based-restrictions.v1.test.js
- Added support for passing the standard X-Correlation-Id header in each request
- Updated some swagger properties summaries and descriptions
This enhancement adds support for passing the standard X-Correlation-Id header in each request. This is an optional header and it does not break backward compatibility.
=> feat(CBR): add support for the X-Correlation-Id header

package-lock.json, package.json
This PR bumps the node core version to 2.17.9 and also bumps the follow-redirects dependency to avoid a snyk vulnerability.
=> fix: bump node core to 2.17.9

examples/iam-identity.v1.test.js, iam-identity/v1.ts, test/integration/iam-identity.v1.test.js, test/unit/iam-identity.v1.test.js
adding new endpoints: create report, get report
adding new optional query parameter include_activity for the existing get calls of apikey/serviceid/profile by id.
users will now be able to generate report for inactive identities.
create report: will return a reference
get report: this will return a detailed report of inactive identities
existing get apikey/serviceid/profile by id will now include additional optional parameter include_activity
if include_activity is passed as true the response will include a new section activity with last authn time and count.
=> feat(IAM Identity): add support for inactivity reports

context-based-restrictions/v1.ts, examples/context-based-restrictions.v1.test.js, test/integration/context-based-restrictions.v1.test.js, test/unit/context-based-restrictions.v1.test.js
enforcement mode support
https://github.ibm.com/IAM/cbr-admin/issues/780
=> feat(Context based Restrictions): enforcement mode support

context-based-restrictions/v1.ts, test/integration/context-based-restrictions.v1.test.js, test/unit/context-based-restrictions.v1.test.js
Signed-off-by: Cameron Davis <cjdavis@ibm.com>
This PR adds CBR support for the new service_group_id parameter in rules.
No current behavior should be modified. Adds the further control to be able to apply rules to service groups
=> add list rule with service_group_id test

.secrets.baseline, enterprise-usage-reports/v1.ts, examples/enterprise-usage-reports.v1.test.js, test/integration/enterprise-usage-reports.v1.test.js, test/unit/enterprise-usage-reports.v1.test.js
This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.
=> fix(Enterprise Usage Reports): regen service to get Pager

examples/iam-policy-management.v1.test.js, iam-policy-management/v1.ts, test/integration/iam-policy-management.v1.test.js, test/unit/iam-policy-management.v1.test.js
Signed-off-by: Shaun Colley <shaun.colley@ibm.com>
Code to support new v2/policies API has been introduced. The new v2/policies API will have new JSON fields and existing v1/fields have been changed.
v1/policies API will continue to be supported.
Also updated test to remove use of callback `done()` with async/await (throws error to use one or other and followed pattern of [access groups](https://github.com/IBM/platform-services-node-sdk/blob/main/test/integration/iam-access-groups.v2.test.js#L77)).
PR's are currently open for staging and production docs. They are not currently merged:
Staging: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/139
Production: …
=> feat(IAM Policy Management): add support for v2/policies

test/unit/usage-reports.v4.test.js, usage-reports/v4.ts
Rename the `billing_month` property in the `Account_Summary` schema to `month`
The `Account_Summary` schema should now correctly have the `month` property instead of the `billing_month` property.
=> fix: rename Account_Summary billing_month property

package-lock.json, package.json, test/integration/enterprise-billing-units.v1.test.js, test/integration/resource-manager.v2.test.js
This updates the Node core to v4, which includes `axios` 1.0 as a
dependency. Since a number of potential issues have been solved by
v1, I'm treating this as a fix so a new release gets published
including the new core version.
=> fix: update core major version

examples/iam-policy-management.v1.test.js
Fixed commented operation id so example generator script will correctly. See operation ids: https://github.ibm.com/cloud-api-docs/iam-access-management/blob/test/iam-policy-management.yaml#L447
No change in behavior, simply will allow generation of sdk examples in api docs.
=> fix(IAM Policy Management): update incorrect example operation id comments to match API definition

examples/iam-identity.v1.test.js, iam-identity/v1.ts, test/integration/iam-identity.v1.test.js, test/unit/iam-identity.v1.test.js
Node SDK doc for IAM identity. PR includes changes related
Create mfa report
Get mfa report
Get mfa user status
Change token expiration max and default value to 259200
=> fix(IAM Identity): re-gen with latest API definition

usage-reports/v4.ts
Updates Account Summary to reflect changes to the API
Updates Account Summary to reflect changes to the API
Integration tests:
```
PASS  test/integration/usage-reports.v4.test.js (7.138 s)
---------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                     
---------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------
All files      |   57.33 |     12.9 |   55.55 |   58.96 | …
```
=> feat(Usage Reports): Update Account Summary

examples/iam-identity.v1.test.js, iam-identity/v1.ts, test/integration/iam-identity.v1.test.js, test/unit/iam-identity.v1.test.js
Added feature support for Trusted Profile identities work, add, get, delete identities associated with the profile. 
SDK adopters will be able to call Trusted profile identities APIs.
API defintion:
[Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api?code=java#get-profile-identities)
Test information:
Integration Tests:
```sh
Tests:       61 passed, 61 total
Time:        51.739 s, estimated 53 s
```
=> feat(IAM Identity): add trusted profile identities api

enterprise-management/v1.ts, test/unit/enterprise-management.v1.test.js
re-gen service after update trait object
=> feat(Enterprise Management): re-gen service after update trait object

examples/iam-policy-management.v1.test.js, iam-policy-management/v1.ts, test/integration/iam-policy-management.v1.test.js, test/unit/iam-policy-management.v1.test.js
Issue: https://github.ibm.com/IAM/AM-issues/issues/1803
**integration results**
**example results**
=> feat(IAM Policy Management): re-gen service after fix the template metadata as part of policies

.gitignore, README.md, examples/partner-billing-units.v1.test.js, partner-billing-units/v1.ts, test/integration/partner-billing-units.v1.test.js, test/unit/partner-billing-units.v1.test.js
Adding new partner APIs to fetch reports of billing options and credits pools services.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/cosell/partner.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2063
=> feat(Partner Billing Units): add new service to project

test/unit/usage-reports.v4.test.js, usage-reports/v4.ts
Regeneration of the usage reports service. Mainly intended to add `catalog_id` to `instance_usage` and `resource`.
Tests:
```
----------------------------|---------|----------|---------|---------|-------------------------------------------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                     
----------------------------|---------|----------|---------|---------|-------------------------------------------------------
All files                   |   98.32 |     89.1 |     100 |   98.28 |                                                       
case-management            |    98.8 |    88.46 |     100 |   98.78 | …
```
=> fix(Usage Reports): re-gen service after recent API changes

.travis.yml, README.md, package-lock.json, package.json
This PR bumps the version of semantic-release in order to avoid a couple of CVEs reported by Mend (micromatch and braces dependencies).
This change made it necessary to bump the min supported Node.js version from 14 to 16, because when building on node 14, the version of npm installed in `node_modules` (because it is a transitive dependency of the newer version of semantic-release pulled in by the newer version of semantic-release) will not run on node v14.
So, it seemed like it's time to move our min supported Node.js version to be 16 and then build on node versions 16, 18, and 20, and semantic-release will be run on node v20.
=> feat(build): bump min supported version of node to 16

catalog-management/v1.ts, examples/catalog-management.v1.test.js, test/integration/catalog-management.v1.test.js, test/unit/catalog-management.v1.test.js
Regenerating after some small API changes.  Need to support install_type param on reloadOffering function for a user.
Only adding new params and routes.
Integration tests
```
Test Suites: 20 skipped, 1 passed, 1 of 21 total
Tests:       406 skipped, 51 passed, 457 total
Time:        31.572 s
Ran all test suites matching /test\/integration\//i.
```
Example tests
```
Tests:       47 passed, 47 total
Time:        27.183 s
Ran all test suites matching /examples\/catalog-management.v1.test.js/i.
```
=> feat(Catalog Management): get regions routes, support install_type param

tsconfig.json
This commit removes comments from the tsconfig.json file in hopes that this will fix a problem seen in the most recent main branch build after changes to the .releaserc file were merged into main.
=> fix(build): remove comments from tsconfig.json

examples/iam-policy-management.v1.test.js, iam-policy-management/v1.ts, test/integration/iam-policy-management.v1.test.js, test/unit/iam-policy-management.v1.test.js
Adds new Access Management Account Settings API (GET and PATCH paths)
Issue: https://github.ibm.com/IAM/AM-issues/issues/3316
=> feat(IAM Policy Management): add access management account settings API

examples/iam-policy-management.v1.test.js, iam-policy-management/v1.ts, test/integration/iam-policy-management.v1.test.js, test/unit/iam-policy-management.v1.test.js
issue: https://github.ibm.com/IAM/AM-issues/issues/3395
=> feat(IAM Policy Management): add support for action control templates from IAM

package-lock.json, package.json
Bump sdk-core to 5.4.2 and axios to 1.11.0 to avoid vulnerabilities.
=> fix(build): bump dependencies to avoid CVEs
